# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete Country by ID

Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

Scenario Outline: Delete country by ID with valid input
    Given path '/country', '/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method delete
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Country deleted successfully'
    And match response.error_info == '##null'

    Examples:
        | id  | app_identifier                                                                 | customer_secret_key                                                                 |
        | 32  | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'                     | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'                     |

Scenario Outline: Delete country by ID with invalid app-identifier
    Given path '/country', '/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method delete
    Then status 401
    And match response.error.code == '##number'
    And match response.error.message == '##string'

    Examples:
        | id  | app_identifier                                                                 | customer_secret_key                                                                 |
        | 32  | 'invalid_app_identifier'                                                             | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'                     |

Scenario Outline: Delete country by ID with invalid customer-secret-key
    Given path '/country', '/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method delete
    Then status 401
    And match response.error.code == '##number'
    And match response.error.message == '##string'

    Examples:
        | id  | app_identifier                                                                 | customer_secret_key                                                                 |
        | 32  | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'                     | 'invalid_customer_secret_key'                                                       |

Scenario Outline: Delete country by ID with invalid ID
    Given path '/country', '/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method delete
    Then status 404
    And match response.error.code == '##number'
    And match response.error.message == '##string'

    Examples:
        | id  | app_identifier                                                                 | customer_secret_key                                                                 |
        | 999 | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'                     | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'                     |
