# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Verify DELETE /country/{id} API functionality

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'
    * header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    * header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'

  Scenario Outline: Successfully delete country by its ID
    Given path 'country/<id>'
    When method DELETE
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.status == 'success'
    And match response.message == '#string'
    And match response.message == 'Country deleted successfully'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id  |
      | 32  |
      | 45  |
      | 100 |

  Scenario: Failure due to missing app-identifier header
    Given path 'country/32'
    * header app-identifier = null
    When method DELETE
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.error.code == '#string'
    And match response.error.message == '#string'

  Scenario: Failure due to missing customer-secret-key header
    Given path 'country/32'
    * header customer-secret-key = null
    When method DELETE
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.error.code == '#string'
    And match response.error.message == '#string'

  Scenario: Failure due to missing ID in the path
    Given path 'country/ '
    When method DELETE
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.error.code == '#string'
    And match response.error.message == '#string'
