# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Get Country by ID

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Get Country by ID with Valid Inputs
    Given path '/country/<id>'
    And header app-identifier = '<app-identifier>'
    And header customer-secret-key = '<customer-secret-key>'
    When method get
    Then status 200
    And match response ==
    """
    {
      status: 'success',
      message: 'Data fetched successfully',
      data: {
        country: {
          id: '#number',
          name: '##string',
          code: 'string',
          default_currency: 'string',
          is_active: '#number',
          app_id: '#number',
          customer_id: '#number',
          created_by: '#number',
          updated_by: '#number',
          created_at: '#string',
          updated_at: '#string',
          currencies: '#[]'
        }
      },
      error_info: '##string'
    }
    """
    And match response.data.country.id == <id>
    And match response.data.country.currencies contains 'INR'
    And match response.data.country.currencies contains 'EURO'
    And match response.data.country.currencies contains 'USD'

    Examples:
      | id  | app-identifier                                      | customer-secret-key                                   |
      | 32  | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d' | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' |

  Scenario: Get Country by ID with Invalid ID
    Given path '/country/abc'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method get
    Then status 400
    And match response ==
    """
    {
      error: {
        code: '#number',
        message: '#string'
      }
    }
    """
    And match response.error.code == 400
    And match response.error.message contains 'Invalid ID'

  Scenario: Get Country by ID with Missing Headers
    Given path '/country/32'
    When method get
    Then status 400
    And match response ==
    """
    {
      error: {
        code: '#number',
        message: '#string'
      }
    }
    """
    And match response.error.code == 400
    And match response.error.message contains 'Missing Headers'

  Scenario: Get Country by ID with Invalid Headers
    Given path '/country/32'
    And header app-identifier = 'invalid'
    And header customer-secret-key = 'invalid'
    When method get
    Then status 401
    And match response ==
    """
    {
      error: {
        code: '#number',
        message: '#string'
      }
    }
    """
    And match response.error.code == 401
    And match response.error.message contains 'Invalid Headers'
