# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=6873c73aa2
# 
# 

# ********RoostGPT********
Feature: Create new country

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Create new country with valid input
    Given path '/country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
    """
    {
      "name": "<name>",
      "code": "<code>",
      "currencies": <currencies>,
      "default_currency": "<default_currency>",
      "is_active": <is_active>
    }
    """
    When method post
    Then status 201
    And match response.status == 'success'
    And match response.message == 'Country created successfully'
    And match response.data.id == '##number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '##string'
    And match response.data.default_currency == '##string'
    And match response.data.is_active == '##number'
    And match response.data.app_id == '##number'
    And match response.data.customer_id == '##number'
    And match response.data.created_by == '##number'
    And match response.data.updated_by == '##number'
    And match response.data.created_at == '##string'
    And match response.data.updated_at == '##string'
    And match response.data.currencies == '##array'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | app_identifier                                                                 | customer_secret_key                                                                 | name   | code | currencies       | default_currency | is_active |
      | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'                   | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'                   | 'INDIA' | 'IND' | ['INR', 'USD', 'EURO'] | 'INR'            | 1          |
