# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=e5eb5af926
# 
# 

# ********RoostGPT********
Feature: Update Country by ID

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update country with valid data
    Given path '/country', '/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
    """
    {
      "name": "<name>",
      "code": "<code>",
      "currencies": <currencies>,
      "default_currency": "<default_currency>",
      "is_active": <is_active>
    }
    """
    When method put
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Country updated successfully'
    And match response.data.id == <id>
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == <code>
    And match response.data.default_currency == <default_currency>
    And match response.data.is_active == <is_active>
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies contains <currencies>
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id | app_identifier | customer_secret_key | name | code | currencies | default_currency | is_active |
      | 32 | d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d | 12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe | INDIA | IND | ['INR', 'USD', 'EURO'] | INR | 1 |
