# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize Laureate API

Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

Scenario Outline: Test GET /2.1/laureate/<laureateID> with valid ID
    * header Accept = 'application/json'
    Given path '/2.1/laureate/<laureateID>'
    When method get
    Then status 200
    And match response ==
    """
    {
        laureate: {
            id: '#number',
            laureateIfPerson: {
                knownName: {
                    en: '#string',
                    se: '#string',
                    'false': '#string'
                },
                givenName: {
                    en: '#string',
                    se: '#string',
                    'false': '#string'
                },
                familyName: {
                    en: '#string',
                    se: '#string',
                    'false': '#string'
                },
                fullName: {
                    en: '#string',
                    se: '#string',
                    'false': '#string'
                },
                filename: '#string',
                penname: '#string',
                gender: '#string',
                birth: {
                    date: '#string',
                    place: {
                        city: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        country: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        cityNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        countryNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        continent: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        locationString: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        }
                    }
                },
                death: {
                    date: '#string',
                    place: {
                        city: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        country: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        cityNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        countryNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        continent: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        locationString: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        }
                    }
                }
            },
            laureateIfOrg: {
                orgName: {
                    en: '#string',
                    se: '#string',
                    'false': '#string'
                },
                nativeName: '#string',
                acronym: '#string',
                founded: {
                    date: '#string',
                    place: {
                        city: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        country: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        cityNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        countryNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        continent: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        locationString: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        }
                    }
                },
                dissolution: {
                    date: '#string',
                    place: {
                        city: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        country: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        cityNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        countryNow: {
                            en: '#string',
                            se: '#string',
                            'false': '#string',
                            sameAs: '#[]'
                        },
                        continent: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        },
                        locationString: {
                            en: '#string',
                            se: '#string',
                            'false': '#string'
                        }
                    }
                },
                headquarters: {
                    city: {
                        en: '#string',
                        se: '#string',
                        'false': '#string'
                    },
                    country: {
                        en: '#string',
                        se: '#string',
                        'false': '#string'
                    },
                    cityNow: {
                        en: '#string',
                        se: '#string',
                        'false': '#string',
                        sameAs: '#[]'
                    },
                    countryNow: {
                        en: '#string',
                        se: '#string',
                        'false': '#string',
                        sameAs: '#[]'
                    },
                    continent: {
                        en: '#string',
                        se: '#string',
                        'false': '#string'
                    },
                    locationString: {
                        en: '#string',
                        se: '#string',
                        'false': '#string'
                    }
                }
            },
            wikipedia: {
                slug: '#string',
                english: '#string'
            },
            wikidata: {
                id: '#string',
                url: '#string'
            },
            sameAs: '#[]',
            links: '#[]',
            nobelPrizes: '#[]'
        }
    }
    """
    Examples:
    | laureateID |
    | 456        |

Scenario Outline: Test GET /2.1/laureate/<laureateID> with invalid ID
    * header Accept = 'application/json'
    Given path '/2.1/laureate/<laureateID>'
    When method get
    Then status <status>
    And match response ==
    """
    {
        code: '#string',
        message: '#string'
    }
    """
    Examples:
    | laureateID | status |
    | 0         | 400    |
    | 99999999  | 404    |
    | -1        | 422    |
