# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
    * configure headers = { Accept: 'application/json' }
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

Scenario Outline: Get Nobel Prize Information
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method get
    Then status <status>
    And match response == '#object'
    And match response.nobelPrize == '#object'
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category == '#object'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.category.false == '#string'
    And match response.nobelPrize.categoryFullName == '#object'
    And match response.nobelPrize.categoryFullName.en == '#string'
    And match response.nobelPrize.categoryFullName.se == '#string'
    And match response.nobelPrize.categoryFullName.false == '#string'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation == '#object'
    And match response.nobelPrize.topMotivation.en == '#string'
    And match response.nobelPrize.topMotivation.se == '#string'
    And match response.nobelPrize.topMotivation.false == '#string'
    And match response.nobelPrize.laureates == '#array'
    And match each response.nobelPrize.laureates[*].id == '#number'
    And match each response.nobelPrize.laureates[*].name == '#object'
    And match each response.nobelPrize.laureates[*].name.en == '#string'
    And match each response.nobelPrize.laureates[*].name.se == '#string'
    And match each response.nobelPrize.laureates[*].name.false == '#string'
    And match each response.nobelPrize.laureates[*].portion == '#string'
    And match each response.nobelPrize.laureates[*].sortOrder == '#string'
    And match each response.nobelPrize.laureates[*].motivation == '#object'
    And match each response.nobelPrize.laureates[*].motivation.en == '#string'
    And match each response.nobelPrize.laureates[*].motivation.se == '#string'
    And match each response.nobelPrize.laureates[*].motivation.false == '#string'
    And match each response.nobelPrize.laureates[*].links == '#array'
    And match each response.nobelPrize.laureates[*].links[*].rel == '#string'
    And match each response.nobelPrize.laureates[*].links[*].href == '#string'
    And match each response.nobelPrize.laureates[*].links[*].action == '#string'
    And match each response.nobelPrize.laureates[*].links[*].types == '#string'

    Examples:
        | category | year | status |
        | 'physics'| 2020 | 200    |
        | 'literature'| 2019 | 200    |
        | 'chemistry'| 2018 | 200    |

Scenario Outline: Get Nobel Prize Information with Invalid Input
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method get
    Then status <status>
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
        | category | year | status |
        | 'invalid'| 2020 | 400    |
        | 'physics'| 1899 | 404    |
        | 'literature'| 2019 | 422    |

