# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Validate Nobel Prize API endpoint /2.1/nobelPrize/{category}/{year}

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Retrieve Nobel Prize information with valid path parameters
    Given path '2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 200
    And match response.nobelPrize.awardYear == ##number
    And match response.nobelPrize.category.en == ##string
    And match response.nobelPrize.category.se == '##string'
    And match response.nobelPrize.category.false == '##string'
    And match response.nobelPrize.categoryFullName.en == ##string
    And match response.nobelPrize.categoryFullName.se == ##string
    And match response.nobelPrize.categoryFullName.false == ##string
    And match response.nobelPrize.dateAwarded == '#regex ^\\d{4}-\\d{2}-\\d{2}$'
    And match response.nobelPrize.prizeAmount == ##number
    And match response.nobelPrize.prizeAmountAdjusted == ##number
    And match response.nobelPrize.topMotivation.en == ##string
    And match response.nobelPrize.topMotivation.se == ##string
    And match response.nobelPrize.topMotivation.false == ##string
    And match each response.nobelPrize.laureates[*].id == '#? _ >= 1'
    And match each response.nobelPrize.laureates[*].name.en == ##string
    And match each response.nobelPrize.laureates[*].name.se == ##string
    And match each response.nobelPrize.laureates[*].name.false == ##string
    And match each response.nobelPrize.laureates[*].portion == '##string'
    And match each response.nobelPrize.laureates[*].sortOrder == '##string'
    And match each response.nobelPrize.laureates[*].motivation.en == ##string
    And match each response.nobelPrize.laureates[*].motivation.se == ##string
    And match each response.nobelPrize.laureates[*].motivation.false == ##string
    And match each response.nobelPrize.laureates[*].links[*].rel == ##string
    And match each response.nobelPrize.laureates[*].links[*].href == ##string
    And match each response.nobelPrize.laureates[*].links[*].action == ##string
    And match each response.nobelPrize.laureates[*].links[*].types == ##string

    Examples:
      | category | year |
      | 'peace'  | 2000 |
      | 'physics'| 1989 |

  Scenario: Validate handling of malformed request syntax
    Given path '2.1/nobelPrize/invalidCategory/invalidYear'
    When method GET
    Then status 400
    And match response.code == '404'
    And match response.message == '#string'

  Scenario: Validate handling of nonexistent resources
    Given path '2.1/nobelPrize/invalidCategory/1900'
    When method GET
    Then status 404
    And match response.code == '404'
    And match response.message == '#string'

  Scenario: Validate handling of semantic errors
    Given path '2.1/nobelPrize/peace/1899'
    When method GET
    Then status 422
    And match response.code == '404'
    And match response.message == '#string'
