# ********RoostGPT********

# Test generated by RoostGPT for test karate-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API

Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

Scenario Outline: Test GET /2.1/nobelPrizes with valid query parameters
    Given path '/2.1/nobelPrizes'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    And param nobelPrizeCategory = <nobelPrizeCategory>
    And param format = <format>
    And param csvLang = <csvLang>
    When method get
    Then status 200
    And match response == '#object'
    And match response.nobelPrizes == '#array'
    And match each response.nobelPrizes[*].awardYear == '#number'
    And match each response.nobelPrizes[*].category == '#object'
    And match each response.nobelPrizes[*].categoryFullName == '#object'
    And match each response.nobelPrizes[*].dateAwarded == '#string'
    And match each response.nobelPrizes[*].prizeAmount == '#number'
    And match each response.nobelPrizes[*].prizeAmountAdjusted == '#number'
    And match each response.nobelPrizes[*].topMotivation == '#object'
    And match each response.nobelPrizes[*].laureates == '#array'
    And match each response.nobelPrizes[*].laureates[*].id == '#number'
    And match each response.nobelPrizes[*].laureates[*].name == '#object'
    And match each response.nobelPrizes[*].laureates[*].portion == '#string'
    And match each response.nobelPrizes[*].laureates[*].sortOrder == '#string'
    And match each response.nobelPrizes[*].laureates[*].motivation == '#object'
    And match each response.nobelPrizes[*].laureates[*].links == '#array'
    And match each response.nobelPrizes[*].laureates[*].links[*].rel == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].href == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].action == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].types == '#string'
    And match response.meta == '#object'
    And match response.meta.offset == '#number'
    And match response.meta.limit == '#number'
    And match response.meta.nobelPrizeYear == '#number'
    And match response.meta.yearTo == '#number'
    And match response.meta.nobelPrizeCategory == '#string'
    And match response.meta.count == '#number'
    And match response.links == '#array'
    And match response.links[*].first == '#string'
    And match response.links[*].prev == '#string'
    And match response.links[*].self == '#string'
    And match response.links[*].next == '#string'
    And match response.links[*].last == '#string'

    Examples:
    | offset | limit | sort | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
    | 1      | 10    | asc  | 1989           | 1999   | eco               | json   | en      |
    | 10     | 20    | desc | 2000           | 2010   | lit               | csv    | sv      |

Scenario: Test GET /2.1/nobelPrizes with invalid query parameters
    Given path '/2.1/nobelPrizes'
    And param offset = 'invalid'
    And param limit = 'invalid'
    When method get
    Then status 400
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

Scenario: Test GET /2.1/nobelPrizes with non-existent query parameters
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 1800
    When method get
    Then status 404
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

Scenario: Test GET /2.1/nobelPrizes with unprocessable query parameters
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 'invalid'
    When method get
    Then status 422
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'
